Repository RhythmusByte/VenueVerse, pull requests merged in 2024-05, with the labels that each got.

#1 Navbar Added
  client/src/App.js
  client/src/components/Navbar.js
  client/src/index.css
  client/src/screens/hdj.txt
Labels: enhancement

#6 Auditorium Route Added
  routes/auditoriumRoute.js
Labels: enhancement

#8 Minor Changes
  client/src/App.js
  routes/auditoriumRoute.js
Labels: bug, enhancement

#10 Minor Fixes
  public/mainpage/details/alb.html
  public/mainpage/details/grand.html
  public/mainpage/details/kaus.html
  public/mainpage/details/new.html
  public/mainpage/details/sion.html
  public/mainpage/details/st.html
  public/mainpage/details/style.css
  public/mainpage/img/logo.png
  public/mainpage/index.html
  public/mainpage/style.css
Labels: enhancement

#15 Improved Readability
  public/mainpage/index.html
  public/mainpage/style.css
Labels: documentation
